name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Coq
      run: sudo apt-get install coq
    - name: Format check
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - name: Linting
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Translate Rust examples
      run: |
        cargo run --bin coq-of-rust -- translate --path examples-from-rust-book
        git -c color.ui=always diff --exit-code
    # - name: Compile Coq translations
    #   run: |
    #     cd coq_translation/examples-from-rust-book ;
    #     coqc -R . CoqOfRust CoqOfRust.v ;
    #     for f in `find . -name "*.v" |sort` ; do
    #       coqc -R . CoqOfRust $f ;
    #     done ;
    #     cd ../..
