name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Coq
      run: sudo apt-get install coq
    - name: Compile Coq examples
      run: find . -name "*.v" |sort |xargs -n 1 coqc
    - name: Format check
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - name: Linting
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Translate Rust examples
      run: |
        cargo run -- translate --path examples-from-rust-book
        git -c color.ui=always diff --exit-code
